[package]
name = "xena"
version = "0.1"
lean_version = "leanprover-community/lean:3.7.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "652fc17a56309b8e90ac2900193585006e14d943"}
